### ISSUE TITLE
Does not scroll-capture PDFs

### ISSUE THREAD

**Issue by mfulton26** [applitools/eyes.extension#1]
I tried this on the [Gmail Motion Printable Guide (PDF)](https://static.googleusercontent.com/media/www.gmail.com/en//mail/help/images/motion/motion_printable_guide.pdf) but it didn't scroll to capture the entire PDF.

**Comment by shahidv3** [comment]
any updates on this issue fix. Appreciate the response

**Comment by danielputerman** [comment]
Hi, for the moment we're not planning to support this functionality via the extension. We do have other solutions for PDFs, please contact support@applitools.com and they'll be happy to provide all the required information.
